DOMAIN = "localhost"
WORLD = "https://world.energyaccessexplorer.org"
TITLE = "Energy Access Explorer"
API_URL = "http://localhost:6789"
STORAGE_URL = "http://localhost:6789/files/"
MAPBOX_THEME = ""
MAPBOX_TOKEN = "pk.eyJ1IjoicmVzb3VyY2V3YXRjaCIsImEiOiJjam54YzhjemcxemNzM3Bta3FkNXk1Z2E1In0.RqblpgU2zkMIsMCP8QPdlQ"
